# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"union": "inventory.ipynb",
         "Endpoints": "inventory.ipynb",
         "InventorySdk": "inventory.ipynb",
         "uploadDf": "inventory.ipynb",
         "ingestData": "inventory.ipynb",
         "branchQuery": "inventory.ipynb",
         "queryAll2": "inventory.ipynb",
         "querySingleProduct2": "inventory.ipynb"}

modules = ["inventory.py"]

doc_url = "https://thanakijwanavit.github.io/villaInventorySdk/"

git_url = "https://github.com/thanakijwanavit/villaInventorySdk/tree/master/"

def custom_doc_links(name): return None
