# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"union": "price.ipynb",
         "Endpoints": "price.ipynb",
         "InventorySdk": "price.ipynb",
         "uploadDf": "price.ipynb",
         "ingestData": "price.ipynb",
         "branchQuery": "price.ipynb",
         "queryAll2": "price.ipynb",
         "querySingleProduct2": "price.ipynb"}

modules = ["inventory.py",
           "price.py"]

doc_url = "https://thanakijwanavit.github.io/villaInventorySdk/"

git_url = "https://github.com/thanakijwanavit/villaInventorySdk/tree/master/"

def custom_doc_links(name): return None
